on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      # - run: docker-compose up -d --build
      - run: docker build -t nidhal/stripe .
      - run: docker run -dp 80:8080 nidhal/stripe
